version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./sql/1-ddl.sql:/docker-entrypoint-initdb.d/1-ddl.sql
      - ./sql/2-dml.sql:/docker-entrypoint-initdb.d/2-dml.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
